// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetCurrentSnapshot() {
  return window['go']['main']['App']['GetCurrentSnapshot']();
}

export function StartCapture(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartCapture'](arg1, arg2, arg3, arg4);
}

export function StopCapture() {
  return window['go']['main']['App']['StopCapture']();
}
