// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: capture_agent.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 控制指令类型
type ControlCommandType int32

const (
	ControlCommandType_UNKNOWN_COMMAND ControlCommandType = 0
	ControlCommandType_START_CAPTURE   ControlCommandType = 1
	ControlCommandType_STOP_CAPTURE    ControlCommandType = 2
	ControlCommandType_SET_CHANNEL     ControlCommandType = 3 // 未来使用
	ControlCommandType_SET_BANDWIDTH   ControlCommandType = 4 // 未来使用
)

// Enum value maps for ControlCommandType.
var (
	ControlCommandType_name = map[int32]string{
		0: "UNKNOWN_COMMAND",
		1: "START_CAPTURE",
		2: "STOP_CAPTURE",
		3: "SET_CHANNEL",
		4: "SET_BANDWIDTH",
	}
	ControlCommandType_value = map[string]int32{
		"UNKNOWN_COMMAND": 0,
		"START_CAPTURE":   1,
		"STOP_CAPTURE":    2,
		"SET_CHANNEL":     3,
		"SET_BANDWIDTH":   4,
	}
)

func (x ControlCommandType) Enum() *ControlCommandType {
	p := new(ControlCommandType)
	*p = x
	return p
}

func (x ControlCommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlCommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_capture_agent_proto_enumTypes[0].Descriptor()
}

func (ControlCommandType) Type() protoreflect.EnumType {
	return &file_capture_agent_proto_enumTypes[0]
}

func (x ControlCommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlCommandType.Descriptor instead.
func (ControlCommandType) EnumDescriptor() ([]byte, []int) {
	return file_capture_agent_proto_rawDescGZIP(), []int{0}
}

// 控制指令消息
type ControlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandType   ControlCommandType     `protobuf:"varint,1,opt,name=command_type,json=commandType,proto3,enum=router_agent.ControlCommandType" json:"command_type,omitempty"`
	InterfaceName string                 `protobuf:"bytes,2,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"` // e.g., "ath1"
	Channel       int32                  `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`                                 // e.g., 1, 6, 11, 36, 149
	Bandwidth     string                 `protobuf:"bytes,4,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`                              // e.g., "HT20", "HT40", "VHT80"
	BpfFilter     string                 `protobuf:"bytes,5,opt,name=bpf_filter,json=bpfFilter,proto3" json:"bpf_filter,omitempty"`             // BPF filter string for tcpdump
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlRequest) Reset() {
	*x = ControlRequest{}
	mi := &file_capture_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRequest) ProtoMessage() {}

func (x *ControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capture_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRequest.ProtoReflect.Descriptor instead.
func (*ControlRequest) Descriptor() ([]byte, []int) {
	return file_capture_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ControlRequest) GetCommandType() ControlCommandType {
	if x != nil {
		return x.CommandType
	}
	return ControlCommandType_UNKNOWN_COMMAND
}

func (x *ControlRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *ControlRequest) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *ControlRequest) GetBandwidth() string {
	if x != nil {
		return x.Bandwidth
	}
	return ""
}

func (x *ControlRequest) GetBpfFilter() string {
	if x != nil {
		return x.BpfFilter
	}
	return ""
}

// 控制指令响应
type ControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlResponse) Reset() {
	*x = ControlResponse{}
	mi := &file_capture_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlResponse) ProtoMessage() {}

func (x *ControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capture_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlResponse.ProtoReflect.Descriptor instead.
func (*ControlResponse) Descriptor() ([]byte, []int) {
	return file_capture_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ControlResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ControlResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 抓包数据消息
type CaptureData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frame         []byte                 `protobuf:"bytes,1,opt,name=frame,proto3" json:"frame,omitempty"` // 原始帧数据 (包含Radiotap)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureData) Reset() {
	*x = CaptureData{}
	mi := &file_capture_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureData) ProtoMessage() {}

func (x *CaptureData) ProtoReflect() protoreflect.Message {
	mi := &file_capture_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureData.ProtoReflect.Descriptor instead.
func (*CaptureData) Descriptor() ([]byte, []int) {
	return file_capture_agent_proto_rawDescGZIP(), []int{2}
}

func (x *CaptureData) GetFrame() []byte {
	if x != nil {
		return x.Frame
	}
	return nil
}

var File_capture_agent_proto protoreflect.FileDescriptor

const file_capture_agent_proto_rawDesc = "" +
	"\n" +
	"\x13capture_agent.proto\x12\frouter_agent\"\xd3\x01\n" +
	"\x0eControlRequest\x12C\n" +
	"\fcommand_type\x18\x01 \x01(\x0e2 .router_agent.ControlCommandTypeR\vcommandType\x12%\n" +
	"\x0einterface_name\x18\x02 \x01(\tR\rinterfaceName\x12\x18\n" +
	"\achannel\x18\x03 \x01(\x05R\achannel\x12\x1c\n" +
	"\tbandwidth\x18\x04 \x01(\tR\tbandwidth\x12\x1d\n" +
	"\n" +
	"bpf_filter\x18\x05 \x01(\tR\tbpfFilter\"E\n" +
	"\x0fControlResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"#\n" +
	"\vCaptureData\x12\x14\n" +
	"\x05frame\x18\x01 \x01(\fR\x05frame*r\n" +
	"\x12ControlCommandType\x12\x13\n" +
	"\x0fUNKNOWN_COMMAND\x10\x00\x12\x11\n" +
	"\rSTART_CAPTURE\x10\x01\x12\x10\n" +
	"\fSTOP_CAPTURE\x10\x02\x12\x0f\n" +
	"\vSET_CHANNEL\x10\x03\x12\x11\n" +
	"\rSET_BANDWIDTH\x10\x042\xad\x01\n" +
	"\fCaptureAgent\x12Q\n" +
	"\x12SendControlCommand\x12\x1c.router_agent.ControlRequest\x1a\x1d.router_agent.ControlResponse\x12J\n" +
	"\rStreamPackets\x12\x1c.router_agent.ControlRequest\x1a\x19.router_agent.CaptureData0\x01B\bZ\x06.;mainb\x06proto3"

var (
	file_capture_agent_proto_rawDescOnce sync.Once
	file_capture_agent_proto_rawDescData []byte
)

func file_capture_agent_proto_rawDescGZIP() []byte {
	file_capture_agent_proto_rawDescOnce.Do(func() {
		file_capture_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_capture_agent_proto_rawDesc), len(file_capture_agent_proto_rawDesc)))
	})
	return file_capture_agent_proto_rawDescData
}

var file_capture_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_capture_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_capture_agent_proto_goTypes = []any{
	(ControlCommandType)(0), // 0: router_agent.ControlCommandType
	(*ControlRequest)(nil),  // 1: router_agent.ControlRequest
	(*ControlResponse)(nil), // 2: router_agent.ControlResponse
	(*CaptureData)(nil),     // 3: router_agent.CaptureData
}
var file_capture_agent_proto_depIdxs = []int32{
	0, // 0: router_agent.ControlRequest.command_type:type_name -> router_agent.ControlCommandType
	1, // 1: router_agent.CaptureAgent.SendControlCommand:input_type -> router_agent.ControlRequest
	1, // 2: router_agent.CaptureAgent.StreamPackets:input_type -> router_agent.ControlRequest
	2, // 3: router_agent.CaptureAgent.SendControlCommand:output_type -> router_agent.ControlResponse
	3, // 4: router_agent.CaptureAgent.StreamPackets:output_type -> router_agent.CaptureData
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_capture_agent_proto_init() }
func file_capture_agent_proto_init() {
	if File_capture_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_capture_agent_proto_rawDesc), len(file_capture_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_capture_agent_proto_goTypes,
		DependencyIndexes: file_capture_agent_proto_depIdxs,
		EnumInfos:         file_capture_agent_proto_enumTypes,
		MessageInfos:      file_capture_agent_proto_msgTypes,
	}.Build()
	File_capture_agent_proto = out.File
	file_capture_agent_proto_goTypes = nil
	file_capture_agent_proto_depIdxs = nil
}
